spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment_risk
    username: payment_risk
    password: payment_risk
  flyway:
    url: jdbc:postgresql://localhost:5432/payment_risk
    user: payment_risk
    password: payment_risk
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: payment_risk
    password: payment_risk
